services:
  gitlab:
    image: gitlab/gitlab-ee:17.6.3-ee.0  # Versión Community Edition (CE)
    container_name: gitlab
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab'
    ports:
      - "8929:80" # Para HTTP
      - "4433:443" # Para HTTPS
      - "2224:22"  # Para SSH 
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - gitlab-network
    depends_on:
      - license_generator

  gitlab-runner:
    image: gitlab/gitlab-runner:v17.8.1
    container_name: gitlab-runner
    restart: always
    depends_on:
      - gitlab
    volumes:
      - gitlab_runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock  # Permite que el runner ejecute contenedores
    networks:
      - gitlab-network

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_runner_config:

networks:
  gitlab-network: