services:
  gitlab:
    image: gitlab/gitlab-ce:latest  # Versión Community Edition (CE)
    container_name: gitlab
    restart: always
    hostname: gitlab.local
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['initial_root_password'] = "admin123"
    ports:
      - "8929:80" # Para HTTP
      - "4433:443" # Para HTTPS
      - "2224:22"  # Para SSH 
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data: