version: "3.8"

services:
  gitlab-license-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gitlab-license-generator
    environment:
      - LICENSE_NAME
      - LICENSE_COMPANY
      - LICENSE_EMAIL
      - LICENSE_PLAN
      - LICENSE_USER_COUNT
      - LICENSE_EXPIRE_YEAR
    volumes:
      - "./license:/app/build"
    stdin_open: true
    tty: true
    restart: "no"
    command: ["./make.sh"]